plugins {
	id 'java'
	id 'jacoco'
	id 'org.springframework.boot' version '4.1.1'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'org.hibernate.orm' version '7.4.5.Final'
	id 'org.graalvm.buildtools.native' version '1.1.8'
}

group = 'com.github.rek655869'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

jacoco {
    toolVersion = "0.8.15" 
}

repositories {
	mavenCentral()
}

configurations {
    mockitoAgent
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	compileOnly 'org.projectlombok:lombok'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	runtimeOnly 'org.xerial:sqlite-jdbc'
	implementation 'org.hibernate.orm:hibernate-community-dialects'
	annotationProcessor 'org.projectlombok:lombok'
	annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
	testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-data-redis-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-validation-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testImplementation 'org.assertj:assertj-core:3.27.3'
	testCompileOnly 'org.projectlombok:lombok'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testAnnotationProcessor 'org.projectlombok:lombok'
}

hibernate {
	enhancement {
	}
}

tasks.named('test') {
	useJUnitPlatform()
	jvmArgs("-javaagent:${configurations.mockitoAgent.asPath}")
	finalizedBy tasks.jacocoTestReport
}

tasks.jacocoTestReport {
	dependsOn tasks.test
	reports {
		xml.required = true 
		html.required = true 
	}
}